### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by mjethani** [rauschma/babel-on-node#2]
```
npm install -g babel
git clone https://github.com/rauschma/babel-on-node.git
cd babel-on-node
npm install
```

Now when you run `npm test`, it fails with the following output:

```

> @ test /Users/mj/Code/test/babel-on-node
> jest

Using Jest CLI v0.4.11
 FAIL  spec/point.spec.js (1.54s)
{}
● Point › it sets up instance properties correctly
  - Expected: undefined toBe: 1
        at Spec.<anonymous> (/Users/mj/Code/test/babel-on-node/spec/point.spec.js:8:21)
  - Expected: undefined toBe: 5
        at Spec.<anonymous> (/Users/mj/Code/test/babel-on-node/spec/point.spec.js:9:21)
1 test failed, 0 tests passed (1 total)
Run time: 2.135s
npm ERR! Test failed.  See above for more details.
```

**Comment by rauschma** [comment]
That is an issue with auto-mocking (which you can’t switch off anymore, because Babel now hoists module imports). I’ve committed a work-around.

**Comment by mjethani** [comment]
This works!

But now it's 2 tests instead of 1. I've submitted a PR to fix this. If we drop the .js extension, jest no longer treats it as a test.

I'm closing this.
